setToggle("cash-out-section", "none")
setToggle("add-money-section", "none")
setToggle("transaction-section", "none")
setToggle("transfer-section", "none")
setToggle("bonus-section", "none")
setToggle("pay-bill-section", "none")


document.getElementById("add-section").addEventListener("click", function() {
    setToggle("cash-out-section", "none")
    setToggle("add-money-section", "block")
    setToggle("default-section", "none")
    setToggle("transaction-section", "none")
    setToggle("transfer-section", "none")
    setToggle("bonus-section", "none")
    setToggle("pay-bill-section", "none")
})
document.getElementById("coshout-section").addEventListener("click", function() {
    setToggle("cash-out-section", "block")
    setToggle("add-money-section", "none")
    setToggle("default-section", "none")
    setToggle("transaction-section", "none")
    setToggle("transfer-section", "none")
    setToggle("bonus-section", "none")
    setToggle("pay-bill-section", "none")
})
document.getElementById("transaction-btn").addEventListener("click", function() {
    setToggle("cash-out-section", "none")
    setToggle("add-money-section", "none")
    setToggle("default-section", "none")
    setToggle("transaction-section", "block")
    setToggle("transfer-section", "none")
    setToggle("bonus-section", "none")
    setToggle("pay-bill-section", "none")
})
document.getElementById("transfer-btn").addEventListener("click", function() {
    setToggle("cash-out-section", "none")
    setToggle("add-money-section", "none")
    setToggle("default-section", "none")
    setToggle("transaction-section", "none")
    setToggle("transfer-section", "block")
    setToggle("bonus-section", "none")
    setToggle("pay-bill-section", "none")
})
document.getElementById("bonus-btn").addEventListener("click", function() {
    setToggle("cash-out-section", "none")
    setToggle("add-money-section", "none")
    setToggle("default-section", "none")
    setToggle("transaction-section", "none")
    setToggle("transfer-section", "none")
    setToggle("bonus-section", "block")
    setToggle("pay-bill-section", "none")
})
document.getElementById("pay-bill-btn").addEventListener("click", function() {
    setToggle("cash-out-section", "none")
    setToggle("add-money-section", "none")
    setToggle("default-section", "none")
    setToggle("transaction-section", "none")
    setToggle("transfer-section", "none")
    setToggle("bonus-section", "none")
    setToggle("pay-bill-section", "block")
})